### PR TITLE
frigholes: wrong destination and added missing optiones for various C type holes

### PR DESCRIPTION
**Pull request by Tupsi**
fixed wrong desto (Q003 always lead to 0.0, not C7). To my knowledge every frighole type could spawn in every wormhole system, so they should be all there for every C type (but this should be discussed as I am not 100% sure). In the meantime added them all, especially to the C1 section as this was empty and there is at least the E004 in there.

### CODE REVIEW

**Comment by Tupsi** [comment]
sorry for the mess. I have no clue what git is saying 3 commits now, where I only wanted to have the init.js changes commited.

**Comment by exodus4d** [comment]
Good question. I got my information from this table:

https://docs.google.com/spreadsheets/d/1U-gjbwwgAHAJdrLXudus2upw99CWiXPe87y2F3ZgS_4/edit?usp=sharing

Unfortunately this table does not seem to be up-2-date. Ill check, if i can´t find any reliable information on the web, we should go with your approach and add them all ;)

**Comment by Tupsi** [comment]
the line for C1s is def. wrong there, can not say much about the rest though. Guess that table was a nice start when these frig holes where new, but then people all forgot about it and buried it down in the grave named internet.

**Comment by Dessix** [comment]
Were any of those `.ini` files important?

**Comment by Tupsi** [comment]
yes, they are important and I messed this up. The idea was to test git in my fork of pathfinder and get rid of these .inis there, NOT merge them to the main project and get them deleted there. I clearly still need some git lessons... :-(

**Pull request closed without merging**
