### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by andrewmunro**
I thought I'd create this pull request to aid other people in setting the project up from scratch easily. It's great for getting started with a development/production environment and I tried to make it as configurable as possible.

Anyway, feel free to reject it if you feel like it doesn't belong here and I'll make it a separate repo.

### CODE REVIEW

**Comment by exodus4d** [comment]
Awesome! Ill look over it, I have no experience with docker so far ;)

```
+RUN npm install
+RUN npm install --global gulp
+RUN gulp ${ENVIRONMENT}
```

If you want to set up a production environment, you will probably run the "production" task, otherwise the "default" (develop) task is executed. The production task will concatinate all JS files into a single file, otherwise your installation will request each JS file which results in a ton of page requests.

```
+RUN gulp production --tag v0.0.15
```

**Comment by andrewmunro** [comment]
I specify the `ENVIRONMENT` environment variable which is set to `production` so by default it will execute `gulp production`, but allows the user to change it at the top easily.

Is the tag required by gulp?

**Comment by exodus4d** [comment]
Not by gulp itselfe. But i use `gulp-param` in the `gulpfile.js` to pass parameter right into the functions.
https://www.npmjs.com/package/gulp-param

The value of the param `--tag` e.g. `v0.0.15` is used to copy the src files (or the minified fieles) to this path: `public/js/v0.0.15/..` . I use this for client site cacheBusting. Each release/version has its own unique path and browsers will not use the outdated JS files when i release a new version.

**Comment by andrewmunro** [comment]
Closing this pull request as it is outdated now. I suggest anyone looking for docker support for this project checks out @DanielGreyborn 's fork https://github.com/DanielGreyborn/pathfinder/tree/develop/docker.

**Pull request closed without merging**
