### PR TITLE
Link signatures to wh connections

### PR DESCRIPTION
**Pull request by garemoko**
Under development. 

When finished will link signatures in the signature panel to specific WH connections, automatically creating new signature records for new WH connections and allowing the user to assign connections to existing signatures. 

This lays the foundation for other developments such as automatically updating the remaining time of the wormhole, and potentially even mass tracking holes.

### CODE REVIEW

**Comment by exodus4d** [comment]
Nice work!
Important hint: Do not edit anything in `public/js/vX.X.X/.... (like:   public/js/v1.1.1/app/ui/system_signature.js) The js files in here will be overwritten from the /js source when running any Gulp task.

**Comment by garemoko** [comment]
@exodus4d gotcha. I'm having to edit those for testing purposes, but I'll be sure to copy all the changes to the js/app/ folder too.

**Comment by Grookshank** [comment]
Please also add a function that deletes signatures in the list and connections on the map together. So if you delete one, it deletes the other.

**Comment by garemoko** [comment]
@Grookshank that's within scope of this PR most likely yes, but feel free to create a separate issue.

**Comment by Tupsi** [comment]
>  I'm having to edit those for testing purposes,
Actuall you don't, check https://github.com/exodus4d/pathfinder/wiki/Build%20process
but do not get fooled like I was in using the "development" way because you are developing as it doesnt stop the process and waits forever for new changes. Use the production option instead and change the version string in pathfinder.ini in line with what you had in the tag field for the npm command.

**Comment by garemoko** [comment]
Note: I'm no longer playing eve so unlikely to finish this PR. feel free to take code from here or close as you see fit.

**Comment by MorpheusXAUT** [comment]
@exodus4d since this is implemented in #290 I guess this PR can be closed?

**Comment by exodus4d** [comment]
@MorpheusXAUT yeah you are right :) Thanks

**Pull request closed without merging**
