### PR TITLE
Parsing multiple languages for signature type (German + English)

### PR DESCRIPTION
**Pull request by Kill4Free**
Adds parsing of german language for signature types.

**Improvements** for later versions:

- Add parsing of signature names
- Add other languages (help needed)

PS: Thanks for making this tool!

### CODE REVIEW

**Comment by Pseude** [comment]
Is it planed to add french too?

**Comment by Kill4Free** [comment]
If you could tell me the translations for the signature names and types. I will add them!
For other languages too. 

Language specific name -> English

**Comment by Kill4Free** [comment]
If you could tell me the translations for the signature names and groups, I'm able to add these. 
(other languages are possible too) 

'Cosmic Anomaly',
'Cosmic Signature'

'Combat site', 
'Relic site', 
etc

**Comment by Pseude** [comment]
Yeah sure, just let me some time to regroup all those names and groups.
Thanks! :)

**Comment by Pseude** [comment]
Do you know if I can find such a list in the installation folder of the game on my computer?
Or do I have to fly through Eve ton make that list?

Where did you found the german names?

**Comment by Kill4Free** [comment]
I haven't used a list.
But I've done exploration many times before and you've got nearly all sites inside a wh.
That would be the easiest way to start.

**Comment by Pseude** [comment]
Yeah I know, for the wh it's easy, but I try to find the sig in LS/HS/NS too.

**Comment by Kill4Free** [comment]
The types and groups are always the same.
The name of the signature is currently not parsed.
So the types and groups would be sufficient :)

**Comment by Pseude** [comment]
Ha! I forgot the most important:

Wormhole -> Trou de verre

**Comment by Kill4Free** [comment]
That should be all! 
I will add it today's evening or tomorrow :) depends on my free time

**Comment by Pseude** [comment]
I made a MISTAKE : 

Wormhole -> Trou de ver


Das ist der Hammer! Vielen Dank!!

**Comment by Kill4Free** [comment]
Added french to the latest version.

(Don't forget you've got to rebuild the js files!)

**Comment by Pseude** [comment]
Great!
Just one thing: data site -> site de **données**  [you wrote site de _donnes_]

Thanks again!

**Comment by Kill4Free** [comment]
Oh my fault I thought I copy pasted. Will correct it tomorrow. 

Thanks!

**Comment by Pseude** [comment]
> (Don't forget you've got to rebuild the js files!)

Weißt du wie ich das machen soll? Ich habe Firefox.

**Comment by Kill4Free** [comment]
Inside the wiki is an article about it. It's serversided it doesn't matter which browser you're using.
[Pathfinder Wiki NodeJs Build](https://github.com/exodus4d/pathfinder/wiki/Node.js)

Der Artikel im Wiki den ich oben gelinkt habe beschreibt das ganze sehr gut.

**Comment by Pseude** [comment]
Perfekt fÿur die Korrektion!
Aber sorry noch mal... Ich verstehe hier gar nichts. Ab '$npm install' funktioniert gar nichts 

> npm WARN enoent ENOENT: no such file or directory, open C:\Users\Komputername\package.json
und so weiter...

und bei 'npm list --depth=0' bekomme ich nur

>C:\Users\Komputername
'-- (empty)

**Comment by dkrotil** [comment]
@Pseude you need to stay in directory , where is the package.json located, in other words, change to root of the pathfinder install and then run npm install.

**Comment by Pseude** [comment]
I do not understand how to make the modifications activ.
How should I change to root of the pathfinder install?

**Comment by Pseude** [comment]
I think I have'nt any elements. Do I need to host Pathfinder myself to use the french terms on Pathfinder?
The changes do not come automatically?

**Comment by Kill4Free** [comment]
Yeah you need to host it yourself. Or you can wait until @exodus4d is merging this into his version.

PS: Sry for the late answer had not really much time.

**Comment by Pseude** [comment]
OK, I understand now.
Alles in Ordnung, das ist perfekt! Danke!

Wenn du die spezifischen Namen auch auf Französisch brauchst, sag einfach Bescheid.

**Comment by h4sk1** [comment]
TL:DR
have you already implemented the German language?`

Regards!

**Comment by Kill4Free** [comment]
Yes it's implemented but it haven't been merged into pathfinder by now.

**Comment by Kill4Free** [comment]
Currently it running on my private pathfinder installation with no issues :-)

**Comment by exodus4d** [comment]
Hi thanks for your work! I´ll have a look at your implementation when `v1.2.3` is released. I´m totally busy with the new [Admin interface (#494)](#494) and _ESI_ improvements, which are scheduled for the  upcoming release for now.

I´m not quite sure if your approach (all languages in a single file) will scale well. When adding more languages to the sig-parser in future. It might be more flexible to have separate language files that can be dynamically required by a client on demand.

**Comment by Kill4Free** [comment]
Thanks for your answer!

The approach is client sided with a regex. It's possible to precompile that regex to improve the performance.
The benefit of this approach is that the user can paste any language and it's automatically accepted.
Currently only the type of the site is parsed and the name is added as description. (Wasn't sure if someone else than me is interested in this feature)
But it would be possible to parse the name too. Then the next step would be to add a language selection for the UI to show the real name from the selected language.

Imho the best would be to parse any language independent of the selection and show the name and type with the selected language.

**Comment by exodus4d** [comment]
@Kill4Free 
> *Hint:* The Gulp build Process will be changed in `v1.2.4`. Please read the updated Wiki, if you are planning to commit Js/Css PRs in future: https://github.com/exodus4d/pathfinder/wiki/GulpJs

**Comment by Kill4Free** [comment]
@exodus4d thanks for the link :)

**Pull request merged**
